# Generated by Django 5.2.7 on 2025-10-22 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_equipment_project_supplier_inspection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='model_no',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_inspection',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supplier',
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(default='default value', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
