# Generated by Django 5.2.7 on 2025-10-23 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_model_no_equipment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Out of Order', 'Out of Order')], default='Good', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='min_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
