# Generated by Django 5.2.7 on 2025-10-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_equipment_category_remove_stockitem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='storage_capacity',
            field=models.FloatField(default=0, help_text='Capacity in barrels or cubic meters'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Natural Gas', 'Natural Gas'), ('LPG', 'LPG')], default='Petrol', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_type',
            field=models.CharField(choices=[('Refinery', 'Refinery'), ('Distributor', 'Distributor'), ('Gas Supplier', 'Gas Supplier'), ('Transporter', 'Transporter')], default='Refinery', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Pump', 'Pump'), ('Compressor', 'Compressor'), ('Storage Tank', 'Storage Tank'), ('Pipeline', 'Pipeline')], max_length=120),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='min_level',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
