# Generated by Django 5.2.7 on 2025-10-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_equipment_storage_capacity_stockitem_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=50)),
                ('capacity', models.CharField(help_text='Total Tank Capacity (e.g., 5000 liters)', max_length=50)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Maintenance', 'Under Maintenance'), ('Inactive', 'Inactive')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_type', models.CharField(choices=[('Tanker', 'Tanker'), ('Truck', 'Truck'), ('Service', 'Service Vehicle'), ('Other', 'Other')], default='Tanker', max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('product_type', models.CharField(help_text='e.g. Petrol, Diesel, Gas', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Litres or KG', max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('checked_by', models.CharField(blank=True, max_length=100)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.supplier')),
            ],
        ),
    ]
